name: NixOS checks
on:
  push:
    paths:
      - 'nixos/**'
  pull_request:
    paths:
      - 'nixos/**'
jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11
      - name: nixfmt
        run: nix-shell -p nixfmt-tree --command "treefmt --ci nixos"
      - name: nix build
        run: nix-build '<nixpkgs/nixos>' -I nixos-config=./nixos/configuration.nix --dry-run
